--- 
dotfiles_files: 
  - .aliases
  - .aliases_clients
  - .bash_profile
  - .bash_prompt
  - .bashrc
  - .curlrc
  - .editorconfig
  - .exports
  - .exports_clients
  - .functions
  - .gdbinit
  - .git
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .gvimrc
  - .hgignore
  - .hushlogin
  - .inputrc
  - .macos
  - .osx
  - .screenrc
  - .tmux.conf
  - .vimrc
  - .wgetrc
  - init/Preferences.sublime-settings
  - "init/Solarized Dark xterm-256color.terminal"
  - "init/Solarized Dark.itermcolors"
  - init/spectacle.json
dotfiles_repo: "https://github.com/TimmersThomas/dotfiles.git"
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Workspace/_Personal/dotfiles
homebrew_cask_apps: []
homebrew_installed_packages: 
  - 
    install_options: with-iri
    name: wget
  - gnu-sed
  - imagemagick
  - ack
  - aircrack-ng
  - aws-cdk
  - aws-cfn-tools
  - awscli
  - awsume
  - bash
  - bash-completion@2
  - bfg
  - cfn-lint
  - dns2tcp
  - dnsmasq
  - fcrackzip
  - findutils
  - git
  - git-flow
  - git-lfs
  - gmp
  - gnupg
  - gradle
  - gradle-completion
  - grep
  - hashpump
  - hydra
  - john
  - maven
  - maven-completion
  - maven@3.2
  - maven@3.3
  - moreutils
  - nmap
  - nvm
  - openssh
  - parquet-tools
  - pigz
  - pv
  - pyenv
  - python@3.9
  - rename
  - rlwrap
  - s3cmd
  - screen
  - sfnt2woff
  - sfnt2woff-zopfli
  - socat
  - sqlmap
  - ssh-copy-id
  - tcpflow
  - tcpreplay
  - tcptrace
  - tree
  - ucspi-tcp
  - webp
  - woff2
  - yarn
  - zopfli

  # APS
  - install_options: cask
    name: 1password
  - install_options: cask
    name: 1password-cli
  - install_options: cask
    name: alfred
  - install_options: cask
    name: amazon-chime
  - install_options: cask
    name: adobe-creative-cloud
  - install_options: cask
    name: adobe-creative-cloud-cleaner-tool
  - install_options: cask
    name: dropbox
  - install_options: cask
    name: balenaetcher
  - install_options: cask
    name: caffeine
  - install_options: cask
    name: cyberduck
  - install_options: cask
    name: docker
  - install_options: cask
    name: docker-compose
  - install_options: cask
    name: evernote
  - install_options: cask
    name: firefox
  - install_options: cask
    name: github
  - install_options: cask
    name: google-chrome
  - install_options: cask
    name: home-assistant
  - install_options: cask
    name: jetbrains-toolbox
  - install_options: cask
    name: macdown
  - install_options: cask
    name: microsoft-teams
  - install_options: cask
    name: notion
  - install_options: cask
    name: postman
  - install_options: cask
    name: sketch
  - install_options: cask
    name: skype
  - install_options: cask
    name: slack
  - install_options: cask
    name: sourcetree
  - install_options: cask
    name: spotify
  - install_options: cask
    name: steam
  - install_options: cask
    name: sublime-text
  - install_options: cask
    name: teamviewer-quickjoin
  - install_options: cask
    name: divvy
  - install_options: cask
    name: the-unarchiver
  - install_options: cask
    name: transmission
  - install_options: cask
    name: tunnelblick
  - install_options: cask
    name: visual-studio-code
  - install_options: cask
    name: open-in-code
  - install_options: cask
    name: vlc
  - install_options: cask
    name: corretto
  - install_options: cask
    name: corretto8
  - install_options: cask
    name: corretto11
homebrew_taps: 
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions
  - bramstein/webfonttools
npm_package: 
  - 
    name: artillery
  - 
    name: depcheck
  - 
    name: http-server
  - 
    name: npm-check-updates
osx_script: "~/.macos --no-restart"
pip_packages: 
  - 
    name: aws-gate
  - 
    name: aws-mfa
  - 
    name: boto3
  - 
    name: botocore
  - 
    name: broadlink
  - 
    name: diagrams
  - 
    name: graphviz
  - 
    name: Jinja2
  - 
    name: PyYAML
  - 
    name: requests
  - 
    name: s3transfer
  - 
    name: toml
post_provision_tasks: 
  - 
    ansible.posix.synchronize: 
      dest: /Users/timmersthomas/
      rsync_opts: 
        - "--hvaHEPRS"
      src: "/Volumes/Extreme SSD/backup_content/"
    name: "Synchronize passing in extra rsync options"
